/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/jwt/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_jwt_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/jwt/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_jwt_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/jwt/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["auth_jwt_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_users_list"];
        put?: never;
        post: operations["auth_users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_users_retrieve"];
        put: operations["auth_users_update"];
        post?: never;
        delete: operations["auth_users_destroy"];
        options?: never;
        head?: never;
        patch: operations["auth_users_partial_update"];
        trace?: never;
    };
    "/api/auth/users/activation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_activation_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_users_me_retrieve"];
        put: operations["auth_users_me_update"];
        post?: never;
        delete: operations["auth_users_me_destroy"];
        options?: never;
        head?: never;
        patch: operations["auth_users_me_partial_update"];
        trace?: never;
    };
    "/api/auth/users/resend_activation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_resend_activation_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/reset_password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_reset_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/reset_password_confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_reset_password_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/reset_username/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_reset_username_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/reset_username_confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_reset_username_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/set_password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_set_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/set_username/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_users_set_username_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/monitoring-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitoring types */
        get: operations["saderat_bank_health_monitoring_monitoring_types_list"];
        put?: never;
        /** Create a monitoring type */
        post: operations["saderat_bank_health_monitoring_monitoring_types_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/monitoring-types/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a monitoring type */
        get: operations["saderat_bank_health_monitoring_monitoring_types_retrieve"];
        /** Replace a monitoring type */
        put: operations["saderat_bank_health_monitoring_monitoring_types_update"];
        post?: never;
        /** Delete a monitoring type */
        delete: operations["saderat_bank_health_monitoring_monitoring_types_destroy"];
        options?: never;
        head?: never;
        /** Update a monitoring type */
        patch: operations["saderat_bank_health_monitoring_monitoring_types_partial_update"];
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/monitorings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitoring reports */
        get: operations["saderat_bank_health_monitoring_monitorings_list"];
        put?: never;
        post: operations["saderat_bank_health_monitoring_monitorings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/monitorings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a monitoring report with its parsed rows */
        get: operations["saderat_bank_health_monitoring_monitorings_retrieve"];
        put: operations["saderat_bank_health_monitoring_monitorings_update"];
        post?: never;
        delete: operations["saderat_bank_health_monitoring_monitorings_destroy"];
        options?: never;
        head?: never;
        patch: operations["saderat_bank_health_monitoring_monitorings_partial_update"];
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/monitorings/upload_excel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload an Excel report */
        post: operations["saderat_bank_health_monitoring_monitorings_upload_excel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/patient-entries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List patient entries
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        get: operations["saderat_bank_health_monitoring_patient_entries_list"];
        put?: never;
        /**
         * Create a patient entry
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        post: operations["saderat_bank_health_monitoring_patient_entries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/patient-entries/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a patient entry
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        get: operations["saderat_bank_health_monitoring_patient_entries_retrieve"];
        /**
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        put: operations["saderat_bank_health_monitoring_patient_entries_update"];
        post?: never;
        /**
         * Delete a patient entry
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        delete: operations["saderat_bank_health_monitoring_patient_entries_destroy"];
        options?: never;
        head?: never;
        /**
         * Update a patient entry
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        patch: operations["saderat_bank_health_monitoring_patient_entries_partial_update"];
        trace?: never;
    };
    "/api/saderat-bank-health-monitoring/patient-entries/presign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign an upload for one file field
         * @description Per-patient entries against a monitoring's field_schema.
         *
         *     Nothing here reads `SaderatBankHealthMonitoring.json`. Entries and the
         *     Excel blob are independent stores that share a key.
         */
        post: operations["saderat_bank_health_monitoring_patient_entries_presign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Activation: {
            uid: string;
            token: string;
        };
        ActivationRequest: {
            uid: string;
            token: string;
        };
        MonitoringType: {
            readonly id: number;
            slug: string;
            name_en: string;
            name_fa: string;
            field_schema?: unknown;
        };
        MonitoringTypeRequest: {
            slug: string;
            name_en: string;
            name_fa: string;
            field_schema?: unknown;
        };
        PasswordResetConfirm: {
            uid: string;
            token: string;
            new_password: string;
        };
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            new_password: string;
        };
        PatchedMonitoringTypeRequest: {
            slug?: string;
            name_en?: string;
            name_fa?: string;
            field_schema?: unknown;
        };
        PatchedPatientEntryRequest: {
            monitoring?: number;
            national_id?: string;
            values?: unknown;
            files?: components["schemas"]["PatientEntryFileRequest"][];
        };
        PatchedSaderatBankHealthMonitoringListRequest: {
            name?: string;
            type?: string;
        };
        PatchedUserRequest: {
            /** Email address */
            email?: string;
        };
        PatientEntry: {
            readonly id: number;
            monitoring: number;
            national_id: string;
            values?: unknown;
            files?: components["schemas"]["PatientEntryFile"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description A stored object. `url` is minted per read and expires. */
        PatientEntryFile: {
            readonly id: number;
            field_key: string;
            key: string;
            original_name: string;
            content_type: string;
            /** Format: int64 */
            size: number;
            readonly url: string | null;
        };
        /** @description A stored object. `url` is minted per read and expires. */
        PatientEntryFileRequest: {
            field_key: string;
            key: string;
            original_name: string;
            content_type: string;
            /** Format: int64 */
            size: number;
        };
        PatientEntryRequest: {
            monitoring: number;
            national_id: string;
            values?: unknown;
            files?: components["schemas"]["PatientEntryFileRequest"][];
        };
        /** @description What the browser must state before Django will sign anything. */
        PresignRequestRequest: {
            monitoring: number;
            national_id: string;
            field_key: string;
            filename: string;
            content_type: string;
            size: number;
        };
        PresignResponse: {
            upload_url: string;
            key: string;
            headers: {
                [key: string]: unknown;
            };
            expires_in: number;
        };
        SaderatBankHealthMonitoringList: {
            readonly id: number;
            name: string;
            type: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        SaderatBankHealthMonitoringListRequest: {
            name: string;
            type: string;
        };
        SaderatBankHealthMonitoringRetrieve: {
            readonly id: number;
            type: string;
            name: string;
            /** Format: date-time */
            readonly created_at: string;
            json?: unknown;
        };
        SaderatBankHealthMonitoringUploadExcelRequest: {
            name: string;
            type: string;
            /** Format: binary */
            file: string;
        };
        SendEmailReset: {
            /** Format: email */
            email: string;
        };
        SendEmailResetRequest: {
            /** Format: email */
            email: string;
        };
        SetPassword: {
            new_password: string;
            current_password: string;
        };
        SetPasswordRequest: {
            new_password: string;
            current_password: string;
        };
        SetUsername: {
            current_password: string;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            new_username: string;
        };
        SetUsernameRequest: {
            current_password: string;
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            new_username: string;
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        UploadExcelResponse: {
            message: string;
        };
        User: {
            /** Email address */
            email?: string;
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            readonly is_staff: boolean;
        };
        UserCreate: {
            /** Email address */
            email?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            readonly id: number;
        };
        UserCreateRequest: {
            /** Email address */
            email?: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            password: string;
        };
        UserRequest: {
            /** Email address */
            email?: string;
        };
        UsernameResetConfirm: {
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            new_username: string;
        };
        UsernameResetConfirmRequest: {
            /**
             * Username
             * @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
             */
            new_username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_jwt_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_jwt_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_jwt_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    auth_users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreateRequest"];
                "multipart/form-data": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
        };
    };
    auth_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this user. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_activation_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ActivationRequest"];
                "multipart/form-data": components["schemas"]["ActivationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activation"];
                };
            };
        };
    };
    auth_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_users_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_users_resend_activation_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SendEmailResetRequest"];
                "multipart/form-data": components["schemas"]["SendEmailResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendEmailReset"];
                };
            };
        };
    };
    auth_users_reset_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SendEmailResetRequest"];
                "multipart/form-data": components["schemas"]["SendEmailResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendEmailReset"];
                };
            };
        };
    };
    auth_users_reset_password_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetConfirm"];
                };
            };
        };
    };
    auth_users_reset_username_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendEmailResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SendEmailResetRequest"];
                "multipart/form-data": components["schemas"]["SendEmailResetRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendEmailReset"];
                };
            };
        };
    };
    auth_users_reset_username_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsernameResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UsernameResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["UsernameResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameResetConfirm"];
                };
            };
        };
    };
    auth_users_set_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SetPasswordRequest"];
                "multipart/form-data": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetPassword"];
                };
            };
        };
    };
    auth_users_set_username_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetUsernameRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SetUsernameRequest"];
                "multipart/form-data": components["schemas"]["SetUsernameRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetUsername"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringType"][];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitoringTypeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MonitoringTypeRequest"];
                "multipart/form-data": components["schemas"]["MonitoringTypeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringType"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monitoring type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringType"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monitoring type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonitoringTypeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MonitoringTypeRequest"];
                "multipart/form-data": components["schemas"]["MonitoringTypeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringType"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monitoring type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The type is still used by monitoring reports. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saderat_bank_health_monitoring_monitoring_types_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this monitoring type. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMonitoringTypeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMonitoringTypeRequest"];
                "multipart/form-data": components["schemas"]["PatchedMonitoringTypeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonitoringType"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaderatBankHealthMonitoringList"][];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
                "multipart/form-data": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaderatBankHealthMonitoringList"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this saderat bank health monitoring. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaderatBankHealthMonitoringRetrieve"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this saderat bank health monitoring. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
                "multipart/form-data": components["schemas"]["SaderatBankHealthMonitoringListRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaderatBankHealthMonitoringList"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this saderat bank health monitoring. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this saderat bank health monitoring. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSaderatBankHealthMonitoringListRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSaderatBankHealthMonitoringListRequest"];
                "multipart/form-data": components["schemas"]["PatchedSaderatBankHealthMonitoringListRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaderatBankHealthMonitoringList"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_monitorings_upload_excel_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SaderatBankHealthMonitoringUploadExcelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadExcelResponse"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientEntry"][];
                };
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientEntryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatientEntryRequest"];
                "multipart/form-data": components["schemas"]["PatientEntryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientEntry"];
                };
            };
            /** @description This patient already has an entry here. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this patient entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientEntry"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this patient entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientEntryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatientEntryRequest"];
                "multipart/form-data": components["schemas"]["PatientEntryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientEntry"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this patient entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this patient entry. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPatientEntryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPatientEntryRequest"];
                "multipart/form-data": components["schemas"]["PatchedPatientEntryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientEntry"];
                };
            };
        };
    };
    saderat_bank_health_monitoring_patient_entries_presign_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PresignRequestRequest"];
                "multipart/form-data": components["schemas"]["PresignRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description The schema does not permit this upload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Object storage unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
